version: "3.8"

x-common-variables: &common-env
  KAFKA_S3_ACCESS_KEY: minioadmin
  KAFKA_S3_SECRET_KEY: minioadmin
  KAFKA_HEAP_OPTS: -Xms1200m -Xmx1200m
  CLUSTER_ID: 5XF4fHIOTfSIqkmje2KFlg

services:
  # MinIO service for S3 storage
  minio:
    container_name: "minio-traffic"
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      automq_net:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Create needed buckets
  mc:
    container_name: "mc-traffic"
    image: minio/mc:RELEASE.2025-05-21T01-59-54Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/automq-data;
      /usr/bin/mc rm -r --force minio/automq-ops;
      /usr/bin/mc mb minio/automq-data;
      /usr/bin/mc mb minio/automq-ops;
      /usr/bin/mc anonymous set public minio/automq-data;
      /usr/bin/mc anonymous set public minio/automq-ops;
      tail -f /dev/null
      "
    networks:
      - automq_net

  # AutoMQ Brokers
  server1:
    container_name: "automq-server1-traffic"
    image: automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$CLUSTER_ID \
        --override node.id=0 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server1:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.cache.size=104857600 \
        --override s3.block.cache.size=20971520 \
        --override s3.wal.upload.threshold=52428800 \
        --override autobalancer.controller.enable=true \
        --override autobalancer.controller.goals=kafka.autobalancer.goals.NetworkInUsageDistributionGoal,kafka.autobalancer.goals.NetworkOutUsageDistributionGoal \
        --override autobalancer.controller.anomaly.detect.interval.ms=30000 \
        --override metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
    ports:
      - "9092:9092"
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

  server2:
    container_name: "automq-server2-traffic"
    image: automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$CLUSTER_ID \
        --override node.id=1 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server2:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.cache.size=104857600 \
        --override s3.block.cache.size=20971520 \
        --override s3.wal.upload.threshold=52428800 \
        --override autobalancer.controller.enable=true \
        --override autobalancer.controller.goals=kafka.autobalancer.goals.NetworkInUsageDistributionGoal,kafka.autobalancer.goals.NetworkOutUsageDistributionGoal \
        --override autobalancer.controller.anomaly.detect.interval.ms=30000 \
        --override metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
    ports:
      - "9093:9092"
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

  server3:
    container_name: "automq-server3-traffic"
    image: automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$CLUSTER_ID \
        --override node.id=2 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server3:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.cache.size=104857600 \
        --override s3.block.cache.size=20971520 \
        --override s3.wal.upload.threshold=52428800 \
        --override autobalancer.controller.enable=true \
        --override autobalancer.controller.goals=kafka.autobalancer.goals.NetworkInUsageDistributionGoal,kafka.autobalancer.goals.NetworkOutUsageDistributionGoal \
        --override autobalancer.controller.anomaly.detect.interval.ms=30000 \
        --override metric.reporters=kafka.autobalancer.metricsreporter.AutoBalancerMetricsReporter
    ports:
      - "9094:9092"
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

networks:
  automq_net:
    name: automq_net_traffic
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.7.0.0/16"
          gateway: "10.7.0.1"
