apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: automq-disk-azure-premium-ssd
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  cachingMode: ReadWrite
  storageAccountType: Premium_LRS
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

